//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Portal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Portal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Portal", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUSCA POR.
        /// </summary>
        internal static string BuscaSocio_BuscaPor {
            get {
                return ResourceManager.GetString("BuscaSocio_BuscaPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Árbitros.
        /// </summary>
        internal static string BuscaSocio_CategoriaArbitros {
            get {
                return ResourceManager.GetString("BuscaSocio_CategoriaArbitros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associados.
        /// </summary>
        internal static string BuscaSocio_CategoriaAssociados {
            get {
                return ResourceManager.GetString("BuscaSocio_CategoriaAssociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediadores.
        /// </summary>
        internal static string BuscaSocio_CategoriaMediadores {
            get {
                return ResourceManager.GetString("BuscaSocio_CategoriaMediadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha uma letra.
        /// </summary>
        internal static string BuscaSocio_Letra {
            get {
                return ResourceManager.GetString("BuscaSocio_Letra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum resultado encontrado!.
        /// </summary>
        internal static string BuscaSocio_NenhumResultado {
            get {
                return ResourceManager.GetString("BuscaSocio_NenhumResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados da Busca por.
        /// </summary>
        internal static string BuscaSocio_ResultadoMenu {
            get {
                return ResourceManager.GetString("BuscaSocio_ResultadoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODOS.
        /// </summary>
        internal static string BuscaSocio_Todos {
            get {
                return ResourceManager.GetString("BuscaSocio_Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faça uma busca.
        /// </summary>
        internal static string Busca_PlaceHolder {
            get {
                return ResourceManager.GetString("Busca_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrativo.
        /// </summary>
        internal static string Contato_Administrativo {
            get {
                return ResourceManager.GetString("Contato_Administrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assunto.
        /// </summary>
        internal static string Contato_Assunto {
            get {
                return ResourceManager.GetString("Contato_Assunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        internal static string Contato_Departamento {
            get {
                return ResourceManager.GetString("Contato_Departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvimento.
        /// </summary>
        internal static string Contato_Desenvolvimento {
            get {
                return ResourceManager.GetString("Contato_Desenvolvimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Contato_Email {
            get {
                return ResourceManager.GetString("Contato_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string Contato_Enviar {
            get {
                return ResourceManager.GetString("Contato_Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financeiro.
        /// </summary>
        internal static string Contato_Financeiro {
            get {
                return ResourceManager.GetString("Contato_Financeiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem.
        /// </summary>
        internal static string Contato_Mensagem {
            get {
                return ResourceManager.GetString("Contato_Mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigado por nos escrever, sua mensagem foi enviada com sucesso e gerou este número de controle.
        /// </summary>
        internal static string Contato_MensagemAgradecimento {
            get {
                return ResourceManager.GetString("Contato_MensagemAgradecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Contato_Nome {
            get {
                return ResourceManager.GetString("Contato_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string Contato_Telefone {
            get {
                return ResourceManager.GetString("Contato_Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTRE EM.
        /// </summary>
        internal static string Contato_Titulo_1 {
            get {
                return ResourceManager.GetString("Contato_Titulo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTATO.
        /// </summary>
        internal static string Contato_Titulo_2 {
            get {
                return ResourceManager.GetString("Contato_Titulo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos do dia.
        /// </summary>
        internal static string EventosDoDia {
            get {
                return ResourceManager.GetString("EventosDoDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos e Programações.
        /// </summary>
        internal static string Home_Agenda_SubTitulo {
            get {
                return ResourceManager.GetString("Home_Agenda_SubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        internal static string Home_Agenda_Titulo {
            get {
                return ResourceManager.GetString("Home_Agenda_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associados Mantenedores.
        /// </summary>
        internal static string Home_Associados {
            get {
                return ResourceManager.GetString("Home_Associados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confira nossos eventos mais próximos.
        /// </summary>
        internal static string Home_Evento_SubTitulo {
            get {
                return ResourceManager.GetString("Home_Evento_SubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximos Eventos.
        /// </summary>
        internal static string Home_Evento_Titulo {
            get {
                return ResourceManager.GetString("Home_Evento_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo e Taxa de Câmbio.
        /// </summary>
        internal static string Home_Informacoes_SubTitulo {
            get {
                return ResourceManager.GetString("Home_Informacoes_SubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações.
        /// </summary>
        internal static string Home_Informacoes_Titulo {
            get {
                return ResourceManager.GetString("Home_Informacoes_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituições Parceiras.
        /// </summary>
        internal static string Home_Instituicoes {
            get {
                return ResourceManager.GetString("Home_Instituicoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqueles que cooperam para estarmos aqui.
        /// </summary>
        internal static string Home_Instituicoes_SubTitulo {
            get {
                return ResourceManager.GetString("Home_Instituicoes_SubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descadastrar.
        /// </summary>
        internal static string Home_NewsLetter_Descadastrar {
            get {
                return ResourceManager.GetString("Home_NewsLetter_Descadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrever-se.
        /// </summary>
        internal static string Home_NewsLetter_Inscrever {
            get {
                return ResourceManager.GetString("Home_NewsLetter_Inscrever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receba nossas news.
        /// </summary>
        internal static string Home_NewsLetter_SubTitulo {
            get {
                return ResourceManager.GetString("Home_NewsLetter_SubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        internal static string Home_NewsLetter_Titulo {
            get {
                return ResourceManager.GetString("Home_NewsLetter_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualize-se com nossas news.
        /// </summary>
        internal static string Home_Noticias_SubTitulo {
            get {
                return ResourceManager.GetString("Home_Noticias_SubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notícias.
        /// </summary>
        internal static string Home_Noticias_Titulo {
            get {
                return ResourceManager.GetString("Home_Noticias_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A republicação e divulgação de conteúdos públicos são permitidas, desde que citados fonte, título e autor. No caso dos conteúdos restritos, não é permitida a utilização sem autorização do responsável. É totalmente livre a citação da URL do Portal (http//www.ccbc.org.br) em sítios e páginas de terceiros..
        /// </summary>
        internal static string Home_Rodape_Aviso {
            get {
                return ResourceManager.GetString("Home_Rodape_Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2014 / 2015 - CCBC - Todos os direitos reservados..
        /// </summary>
        internal static string Home_Rodape_DireitosAutorais {
            get {
                return ResourceManager.GetString("Home_Rodape_DireitosAutorais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAIBA MAIS.
        /// </summary>
        internal static string Home_Saiba_Mais {
            get {
                return ResourceManager.GetString("Home_Saiba_Mais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conheça mais sobre o CAM CCBC.
        /// </summary>
        internal static string Home_SobreNos_SubTitulo {
            get {
                return ResourceManager.GetString("Home_SobreNos_SubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre Nós.
        /// </summary>
        internal static string Home_SobreNos_Titulo {
            get {
                return ResourceManager.GetString("Home_SobreNos_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + ver todos.
        /// </summary>
        internal static string Home_Ver_Todos {
            get {
                return ResourceManager.GetString("Home_Ver_Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxa de Câmbio.
        /// </summary>
        internal static string Informacao_TaxaCambio {
            get {
                return ResourceManager.GetString("Informacao_TaxaCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-vindo.
        /// </summary>
        internal static string Login_Mensagem_BemVindo {
            get {
                return ResourceManager.GetString("Login_Mensagem_BemVindo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quer se desconectar?.
        /// </summary>
        internal static string Login_Mensagem_Desconectar {
            get {
                return ResourceManager.GetString("Login_Mensagem_Desconectar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fique à vontade, conteúdos exclusivos.
        /// </summary>
        internal static string Login_Mensagem_FiqueAvontade {
            get {
                return ResourceManager.GetString("Login_Mensagem_FiqueAvontade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login inválido. Acesso Negado!.
        /// </summary>
        internal static string Login_Mensagem_Invalido {
            get {
                return ResourceManager.GetString("Login_Mensagem_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string Login_Sair {
            get {
                return ResourceManager.GetString("Login_Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conteúdo exclusivo p/ associados.
        /// </summary>
        internal static string Login_Subtitulo {
            get {
                return ResourceManager.GetString("Login_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login para acesso restrito.
        /// </summary>
        internal static string Login_Titulo {
            get {
                return ResourceManager.GetString("Login_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro.
        /// </summary>
        internal static string MinhaConta_Cadastro {
            get {
                return ResourceManager.GetString("MinhaConta_Cadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENVIAR.
        /// </summary>
        internal static string NewsLetter_Botao {
            get {
                return ResourceManager.GetString("NewsLetter_Botao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        internal static string NewsLetter_Email {
            get {
                return ResourceManager.GetString("NewsLetter_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string NewsLetter_Nome {
            get {
                return ResourceManager.GetString("NewsLetter_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Campos de preenchimento obrigatório.
        /// </summary>
        internal static string NewsLetter_Obrigatorio {
            get {
                return ResourceManager.GetString("NewsLetter_Obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACESSO RESTRITO.
        /// </summary>
        internal static string QuickMenu_AcessoRestrito {
            get {
                return ResourceManager.GetString("QuickMenu_AcessoRestrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        internal static string QuickMenu_Icon_Contato {
            get {
                return ResourceManager.GetString("QuickMenu_Icon_Contato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário efetuar o login na área de acesso restrito acima..
        /// </summary>
        internal static string QuickMenu_NecessarioLogin {
            get {
                return ResourceManager.GetString("QuickMenu_NecessarioLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimento Online.
        /// </summary>
        internal static string QuickMenu_ProcedimentoOnline {
            get {
                return ResourceManager.GetString("QuickMenu_ProcedimentoOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontre o que procura.
        /// </summary>
        internal static string QuickMenu_Subtitulo {
            get {
                return ResourceManager.GetString("QuickMenu_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Menu.
        /// </summary>
        internal static string QuickMenu_Titulo {
            get {
                return ResourceManager.GetString("QuickMenu_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre em Contato.
        /// </summary>
        internal static string Rodape_Contato {
            get {
                return ResourceManager.GetString("Rodape_Contato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização.
        /// </summary>
        internal static string Rodape_Localizacao {
            get {
                return ResourceManager.GetString("Rodape_Localizacao", resourceCulture);
            }
        }
    }
}
