//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitePortal.WCFIntegracaoPortal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaMenuResponse", Namespace="http://schemas.datacontract.org/2004/07/DTO.Menu")]
    [System.SerializableAttribute()]
    public partial class ListaMenuResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SitePortal.WCFIntegracaoPortal.Menu[] MenusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SitePortal.WCFIntegracaoPortal.Menu[] Menus {
            get {
                return this.MenusField;
            }
            set {
                if ((object.ReferenceEquals(this.MenusField, value) != true)) {
                    this.MenusField = value;
                    this.RaisePropertyChanged("Menus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Menu", Namespace="http://schemas.datacontract.org/2004/07/DTO.Menu")]
    [System.SerializableAttribute()]
    public partial class Menu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MenuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MenuPaiIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MenuTipoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RotuloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkURL {
            get {
                return this.LinkURLField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkURLField, value) != true)) {
                    this.LinkURLField = value;
                    this.RaisePropertyChanged("LinkURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuId {
            get {
                return this.MenuIdField;
            }
            set {
                if ((this.MenuIdField.Equals(value) != true)) {
                    this.MenuIdField = value;
                    this.RaisePropertyChanged("MenuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MenuPaiId {
            get {
                return this.MenuPaiIdField;
            }
            set {
                if ((this.MenuPaiIdField.Equals(value) != true)) {
                    this.MenuPaiIdField = value;
                    this.RaisePropertyChanged("MenuPaiId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MenuTipoId {
            get {
                return this.MenuTipoIdField;
            }
            set {
                if ((this.MenuTipoIdField.Equals(value) != true)) {
                    this.MenuTipoIdField = value;
                    this.RaisePropertyChanged("MenuTipoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rotulo {
            get {
                return this.RotuloField;
            }
            set {
                if ((object.ReferenceEquals(this.RotuloField, value) != true)) {
                    this.RotuloField = value;
                    this.RaisePropertyChanged("Rotulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFIntegracaoPortal.IIntegracaoPortal")]
    public interface IIntegracaoPortal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoPortal/GetTestService", ReplyAction="http://tempuri.org/IIntegracaoPortal/GetTestServiceResponse")]
        bool GetTestService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoPortal/ListarMenu", ReplyAction="http://tempuri.org/IIntegracaoPortal/ListarMenuResponse")]
        SitePortal.WCFIntegracaoPortal.ListaMenuResponse ListarMenu(int MenuTipoId, System.Nullable<int> MenuPaiId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegracaoPortalChannel : SitePortal.WCFIntegracaoPortal.IIntegracaoPortal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegracaoPortalClient : System.ServiceModel.ClientBase<SitePortal.WCFIntegracaoPortal.IIntegracaoPortal>, SitePortal.WCFIntegracaoPortal.IIntegracaoPortal {
        
        public IntegracaoPortalClient() {
        }
        
        public IntegracaoPortalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegracaoPortalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracaoPortalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracaoPortalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetTestService() {
            return base.Channel.GetTestService();
        }
        
        public SitePortal.WCFIntegracaoPortal.ListaMenuResponse ListarMenu(int MenuTipoId, System.Nullable<int> MenuPaiId) {
            return base.Channel.ListarMenu(MenuTipoId, MenuPaiId);
        }
    }
}
