/*select * from tblAssociado where SiteId = 1 And AssociadoCategoriaId = 1 And TipoPessoaId = 1 and AssociadoId < 116
delete from tblAssociado where SiteId = 1 And AssociadoCategoriaId = 1 And TipoPessoaId = 1 and AssociadoId < 116
select * from tblAssociado where AssociadoId > 116
update tblAssociado set TipoPessoaId = 2 where AssociadoId > 116

Select * from tblAssociado Where Resumo like '%pessoa física%' and AssociadoId > 116
update tblAssociado set TipoPessoaId = 1 Where Resumo like '%pessoa física%' and AssociadoId > 116
*/

Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, '1857 Comércio e Exportação de Café Ltda. ', 'A 1857 é uma empresa familiar com tradição secular em café. Trabalha com as principais certificações internacionais (UTZ, BSCA) além de parceria com Fairtrade, buscando assegurar a qualidade dos produtos entregues aos clientes, com impecável segurança alimentar, respeitando a natureza e o desenvolvimento social da comunidade local.  ', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Ad Souza ME', 'Assessoria Econômica / Financeira', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Antonio Luiz Sampaio Carvalho', 'A especialização em assuntos de mineração e em suas matérias complementares possibilita ao Escritório a prestação de assistência completa aos clientes, com orientação e execução dos procedimentos jurídicos adequados, dentro dos preceitos de elevados padrões éticos e morais.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Aecometric Corporation ', '', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'AG Indústria e Comércio de Placas Eletrônicas Ltda. ', 'Certificada por normas internacionais e qualidade a AG é uma montadora de placas eletrônicas que oferece desde o serviço de montagem das placas até o full turn key. Tem como diferencial a flexibilidade e customização dos produtos. Possui maquinário avançado e estrutura moderna para garantir a satisfação completa dos nossos parceiros.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Air Canada', 'É a maior empresa aérea do Canadá, servindo mais de 175 destinos nos cinco continentes. A empresa de bandeira do Canadá oferece voos non stop diários de São Paulo para Toronto, com conexões imediatas para 59 cidades canadenses, 56 destinos nos EUA e 63 cidades na Europa, Oriente Médio, Ásia, Austrália, Caribe, México e América do Sul.  Membro fundador da Star Alliance, que serve 1.356 destinos em 193 países. Em 2011 e 2012 a Air Canada foi eleita a Melhor Companhia Aérea da América do Norte em uma pesquisa conduzida pela empresa independente SKYTRAX.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Airlounge Assessoria & Consultoria Administrativa', 'Consultoria na compra e venda de aeronaves novas e usadas. Representante exclusiva da Edmiston, uma das líderes mundiais no mercado.  ', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Alan Kenigsberg ', 'Alan Kenigsberg (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Alberta School Of Business University of Alberta', '', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Alencar Ferreira', 'Alencar Ferreira (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Alexandre Gustavo Freire da Silva Caldas ', 'Alexandre Gustavo Freire da Silva Caldas (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Aline Costa de Carvalho ', 'Aline Costa de Carvalho (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Allen & Overy Serviços de Consultoria Ltda.', 'Setores de Atuação:
Energia; Instituições Financeiras; Hotéis e Lazer; Industriais e de produção; Infra-estrutura e Transporte; Ciências da Vida: Mineração e Metais; Private Equity; Imobiliária; Varejo e Bens de Consumo; Telecomunicações, Media e Tecnologia.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Allori Business Solutions', 'Seja qual for o modelo do seu negócio (com ou sem fins lucrativos), o objetivo é sempre encontrar a maneira mais eficiente e eficaz para operar a sua empresa a alcançar o máximo de resultado. Nós desenvolvemos um processo de avaliação estratégica que compreende cinco aspectos fundamentais de negócio que determinam o direcionamento de recursos e ações que terão o maior impacto sobre o desempenho de sua empresa.
Gestão Estratégica e Financeira / Marketing / Supply Chain / Sistemas de Informação / Desenvolvimento Organizacional.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Almeida Advogados ', 'O Almeida Advogados é um escritório completo com ampla atuação em todos os segmentos do direito corporativo, desde a consultoria empresarial, estruturação de operações e prevenção de litigios, até o contencioso em geral.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Alvaro Philippe Sant´Anna Barretto ', 'Investidor procurando oportunidade para investir no Canadá.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Luciana Amario da Silva', '', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Ana Carolina Beneti', '', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Ancar Invanhoe Shopping Centers', 'A empresa atua em todos os aspectos da gestão de um shopping center, através de uma equipe altamente motivada, que acompanha diariamente a evolução dos shopping centers do grupo, otimizando custos e priorizando as inovações do mercado.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Anderson Alexandre da Silva', 'Tradutor Público e Intérprete Comercial
Traducteur Public Assermenté – Langue Française
Traduções & Versões Juramentadas no Idioma Francês
Cinco Anos de Experiência no Mercado
Livros Traduzidos do Francês e Publicados no Brasil.
Tel. +55 11 2901-7694 – Celular +55 11 98522-0954
anderson22tradutor@hotmail.com', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Andrade Comercial ', 'Fornecimento de alimentos preparados preponderantemente para empresas.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'André Machado Gomes', 'Advogado em São Paulo. 
Especialista em Direito Empresarial pela PUC-SP.
Atua em Direito Societário, Tributário, Concorrencial, Propriedade Intelectual, Trabalhista.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Armstrong Fluid Technology do Brasil - Indústria e Comércio Ltda. ', 'Empresa canadense que fornece produtos, sistemas e serviços para aplicação em sistemas de ar condicionado central, mineração. Na área de ar condicionado central destaca-se no fornecimento de soluções de eficiência para esse sistema e na área de mineração fornece sistemas de bombeamento para maquinas e instalações.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Ascensus Comercio Internacional Ltda.', 'Serviços em soluções completas em operações de importação e exportação e apoio em todo processo tributário, logístico e aduaneiro. Com o diretor Sr. Peter, disponível para clientes de fora do Brasil.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Augelli e Zioni Advogados', 'O escritório foca na prestação de serviços jurídicos nas áreas preventiva, consultiva e litigiosa, tendo como principal objetivo atender, de forma personalizada, aos interesses de seus Clientes, de modo a garantir a excelência dos serviços prestados para cada caso, oferecendo soluções eficazes e criativas para os mais complexos e variados assuntos do Direito.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Aura Minerals Inc. Aura Gold Mineração Ltda.', 'Aura Minerals é uma empresa canadense mid-tier ouro e produção de cobre com foco no desenvolvimento e operação de projetos de ouro e metais nas Américas.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'B.A.M & A Corporate Finance', 'Liderando boutique de banco de investimento da América Latina criada em 1997. 
Cobrindo a América Latina a partir de nossos escritórios em São Paulo (Brasil), Buenos Aires (Argentina), Bogotá (Colômbia), Lima (Peru), Montevidéu (Uruguai), Cidade do México (México) e Miami. 
Principais serviços: transfronteiriça M & A / Consultoria Financeira Corporativa / captação de recursos.
Alcance global eficiente e presença local na Europa, América Latina, EUA e Ásia.
Membro exclusivo para a América Latina da Translink Corporate Finance AG - uma rede global líder de banca de investimento independente e empresas de finanças corporativas.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Behaviour Interactive Inc.', 'É uma empresa canadense que desenvolve jogos:
Console, MMO,  Móvel e Digital.
Uma cultura empresarial que promove oportunidades de todos os tipos e dá a todos a sensação de fazer a diferença.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Blackberry', 'SmartPhones; Software para Desktop; Software para SmartPhones; Software Empresarial; BBM -  mensageiro instantâneo gratuito da marca BlackBerry, que chegou oficialmente e de forma gratuita para aparelhos com os sistemas operacionais móveis Android, iOS e Windows Phone.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'BMO Capital Markets Bank of Montreal Assessoria e Serviços Ltda.', 'Fundada em 1817 como Bank of Montreal, BMO Financial Group (TSX, NYSE: BMO) é uma organização de serviços financeiros altamente diversificada. Com ativos totais de 589.000 milhões dólares americanos a partir de 31 outubro de 2014, e mais de 46.000 funcionários, BMO fornece uma ampla gama de serviços bancários de varejo, gestão de patrimônio e de produtos de banco de investimento e soluções.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Bombardier Transportation Brasil Ltda.', 'Como a única fabricante do mundo de aviões e trens, nós construímos um portfólio extenso e diversificado de ganhar soluções de mobilidade. Em todos os lugares as pessoas viajam por terra e no ar, um produto Bombardier está pronto para transportá-los. A partir de jatos comerciais de definição de categorias e aeronaves comerciais projetado para os desafios de hoje, para trens de alta velocidade elegantes e transporte público que é mais inteligente do que nunca.
A Bombardier está sediada em Montreal, Canadá.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Bonassa Bucker Advogados', 'Agregando conhecimentos e experiências em diversos segmentos econômicos, o escritório está habilitado a fornecer serviços jurídicos relativos à legislação local e internacional a empresas com atuação nas áreas de prestação de serviços, industrial, comercial, de tecnologia da informação e ainda a órgãos públicos e câmaras legislativas.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Boyden do Brasil Ltda.', 'Atua na busca e seleção de executivos para empresas nos mais diversos setores da economia, de operações de grande porte a start ups.  Com presença global, tem escritórios em Toronto, Calgary e Winnipeg. Em São Paulo, John Murray é o sócio responsável pelo relacionamento com a CCBC e sua comunidade, além de coordenar a Comissão de Assuntos Econômicos.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'BPC Partners ', '', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'BR-AR Comercial Importadora e Exportadora e Comércio de Alimentos Ltda.', 'Importadora e exportadora de produtos alimentícios.
Atividade principal - Comércio atacadista de farinhas, amidos e féculas.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Briganti Advogados', 'Foco de atuação empresarial especializado em direito tributário, societário e administrativo.
Realiza a gestão dos interesses legais, por meio do seu corpo técnico ou da rede de relacionamentos construída ao longo dos anos, proporcionando tranquilidade na condução do seu core business.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Brookfield Brasil Ltda.', 'Subsidiária integral da Brookfield Asset Management Inc,, é uma das maiores plataformas de investimento no país, com aproximadamente 7.800 funcionários e mais de R$ 25 bilhões de ativos sob gestão. Como gestora de ativos alternativos investimos e operamos no Brasil desde 1899, com foco nos setores imobiliário, de infraestrutura, florestal, agropecuário, de private equity e financeiro.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'CAE South America Flight Training do Brasil Ltda.', 'Líder global no fornecimento de soluções de treinamento abrangentes com base em tecnologia de simulação de voos. Uma gama completa de soluções altamente inovadoras de produtos, de serviços e do centro de formação destinadas as  necessidades de missão crítica para a segurança, eficiência e prontidão. Oferece soluções semelhantes para os clientes na área da saúde e mineração. CAE tem a maior base instalada de simuladores de voo civis e militares. Com mais de 230 simuladores de voo completos em 50 locais de treinamento civis em todo o mundo. Tem a maior rede de locais de treinamento civis na indústria, atendendo a aproximadamente 3.500 companhias aéreas, operadores de aeronaves e fabricantes de todo o mundo.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Caeli Comércio Importação e Exportação de Bens e Serviços Ltda. ', 'Comércio atacadista de mercadorias em geral, sem predominância de alimentos ou de insumos agropecuários.
Atividades de intermediação e agenciamento de serviços e negócios em geral, exceto imobiliários.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'CAP - Amazon Marketing e Investimento Ltda', 'É uma agência de marketing, eventos e relações públicas, especializada em turismo, vinhos e lifestyle.
Além de representar a Sopexa, agência de promoção dos vinhos da França, a Cap Amazon representa também Amazon Santana, empresa de cruzeiros fluviais na Amazônia, e o blog Brasil a Francesa.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Cargill Agricola S.A. ', 'Produzimos e comercializamos internacionalmente produtos e serviços alimentícios, agrícolas, financeiros e industriais. Em parceria com produtores, clientes, governos e comunidades, e por meio de nossos quase 150 anos de experiência nós ajudamos a sociedade a prosperar. Temos 142 mil  em 67 países.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'CAS Business Solutions Eireli ME', 'Seu escritório de comércio exterior no Brasil, ajudando a sua empresa crescer.
Desenvolvimento de negócios internacionais. Trabalha como um parceiro em busca de novas empresas que querem fazer negócios com o Brasil.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Cesar Watanabe de Toledo ', 'Executivo com 20 anos de atuação, e experiência internacional na América Latina e no Oriente Médio, na industria automotiva na áreas de venda, marketing e pós venda. ', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'CN Worldwide Serviços de Logística Internaticional Ltda.', 'Seja qual for o produto, podemos movê-lo. Temos a experiência, o alcance da rede, a capacidade de transportar o seu produto da origem ao destino com segurança, em tempo útil e de forma rentável.
Mesmo se você não está localizado na nossa linha de trem ou navio, tenha grandes volumes, podemos oferecer-lhe uma solução completa para o transporte.
A CN oferece o único serviço de estrada de ferro da América do Norte, que se estende para três costas, incluindo os serviços para o México, América do Sul e Ásia.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Comércio e Exportação de Café Eireli ', 'Importação e exportação de café.
A COCCAMP foi constituída para atuar no segmento da cafeicultura, oferecendo serviços bem diversificados. Nesse segmento, a empresa vem se consolidando com grande sucesso há 10 anos.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Council of Atlantic Premiers ', 'Fundada em maio de 2000, com a assinatura do Memorando de Entendimento sobre a colaboração regional, o Conselho da missão Premiers Atlântico é promover a colaboração entre as quatro províncias do Atlântico. Premiers o compromisso de trabalhar em conjunto e com o governo federal em questões de importância para todos os canadenses do Atlântico, incluindo aumento de oportunidades de comércio, apoio à investigação e desenvolvimento, o investimento em iniciativas de energia renovável e cooperação econômica e social.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'CSV Assessoria Empresarial', 'Orientação para profissionalização de atividades empresariais; -Organização documental para funcionamento empresarial; -Organização empresarial por segmentos econômicos; -Orientação sobre a formação de empresas; -Orientação sobre procedimentos de cobranças ativa e passiva; -Análise documental na contratação com terceiros; -Análise de assuntos e questões de interesse da empresa. -Orientação para a regularização de custos/despesas; -Consultoria para a recuperação de créditos.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'De Coster Serviços de Apoio ao Comércio Internacional Ltda. - EPP', 'A Managium é uma consultoria em comércio exterior de origem canadense, acompanhando empresas tecnológicas brasileiras e estrangeiras no desenvolvimento das suas atividades nos mercados da America Latina, Canadá e Europa.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Demarest  Advogados', 'É um dos mais conceituados escritórios de advocacia do Brasil e um dos maiores da América Latina. Tem por objetivo prestar serviços jurídicos nas mais diversas áreas do Direito Empresarial.
Áreas de atuação Direito Societário, Bancário, Trabalhista, Regulatório, Tributário, Comércio Internacional, Econômico e Concorrencial, Seguros e Previdência e Reestruturação de Empresas - se refletem cotidianamente o conhecimento e experiência de nossos profissionais.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'DGCA Consultoria e Comunicação Ambiental', 'Empresa focada em disponibilizar as mais eficientes e avançadas ferramentas em Comunicação Ambiental Integrada. Oferece um planejamento estratégico que contempla todas as etapas dos processos comunicativos internos e externos dos nossos parceiros.
A Comunicação Ambiental Integrada difere-se dos sistemas comunicativos padrões por necessitar de uma linguagem singular e técnica que contemple o entendimento pleno por diversos níveis de receptores.
Frente à crescente abordagem das questões ambientais na mídia e nas redes sociais — muitas empresas têm encontrado dificuldades para prevenir ou gerir crises que envolvam aspectos institucionais ou mercadológicos. A DGCA oferece aos seus clientes o suporte necessário para preservar, com eficiência e solidez, o ativo mais importante da sua empresa: a sua reputação.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Dobroy & Partners International Consultants in Leadership', 'Fundada em 1983 por dois ex-diretores da SpencerStuart, é um “quality leader” no setor de recrutamento de executivos, trabalhando sob o regime de “retainer fees”. Operando em escala global, tem larga experiência em níveis de Presidente/CEO, diretoria e alta gerência. Ajudar aos clientes atrair os profissionais de alta performance que necessitam para lidar com as mudanças e atingir os objetivos estratégicos de suas empresas. Os serviços de consultoria incluem Avaliação Gerencial, Governança Corporativa (consultoria para a criação de Conselhos de Administração eficazes), e o recrutamento de Diretores Não-Executivos.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Douglas de Oliveira Pavão ', 'Douglas de Oliveira Pavão (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Embraer S.A.', 'Uma das maiores empresas aeroespaciais do mundo, com mais de 40 anos de existência, atuando nas etapas de projeto, desenvolvimento, fabricação, venda e suporte pós-venda de aeronaves para os segmentos de aviação comercial, aviação executiva, além de oferecer soluções integradas para defesa e segurança e sistemas. 
Com escritórios e fábricas em várias partes do mundo e mais de cinco mil aeronaves vendidas em todos os continentes, é líder no mercado de jatos comerciais com até 130 assentos, a quinta maior fabricante de jatos executivos no mundo e a maior Empresa de soluções de defesa e segurança no Brasil.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Emdoc São Paulo - Serviços Especializados Ltda.', '', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Enville Inc. ', '', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Escritório do Governo de Quebec em São Paulo', 'Auxilia as empresas com informações sobre a Província de Quebec.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Export Development Canadá', 'Ajuda a vender produtos ou serviços fora do Canadá ou investir em mercados estrangeiros. Oferece uma gama de finanças, seguros e de ligação soluções para os exportadores canadenses e investidores que fazem negócios em todo o mundo.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Eza Representação Comercial e Consultoria Ltda. ', 'Atividades de consultoria em gestão empresarial, exceto consultoria técnica específica.
Representantes comerciais e agentes do comércio de combustíveis, minerais, produtos siderúrgicos e químicos.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'F. Theophilo Advocacia Empresarial ', 'Possuía atuação específica na área tributária. Também atua na área empresarial nos campos cível, comercial, societário e administrativo. 
O campo de atuação do escritório é a região de Londrina, e atua ainda junto aos Tribunais Superiores com correspondentes em Curitiba, Porto Alegre e Brasília.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Fabio Silveira Vilella ', 'Fabio Silveira Vilella (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Fairfax Brasil Seguros Corporativos S.A.', 'Soluções inovadoras e diferenciadas na transferência de riscos corporativos para empresas multinacionais que operam em diferentes países.
Como parte da estratégia de atuação na America Latina, a Fairfax Brasil concluiu a renovação dos seus principais contratos de resseguro estendendo capacidade automática para as seguintes linhas de negócios: Infraestrutura / Óleo & Gás / Garantia / Aeronáutico / Transporte / Riscos Diversos.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Falcon Metais Ltda.', 'Empresa de mineração.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Felipe Cattani', 'Felipe Cattani (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Felsberg Advogados', 'Atua nas principais áreas do Direito, com larga experiência na estruturação de negócios complexos, como privatizações, project finance, reestruturações de empresas, fusões e aquisições, sempre orientado pela excepcional qualidade e pelo atendimento personalizado.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Finkelstein Advogados ', 'É um escritório boutique dedicado a consultoria em assuntos empresariais, societários e de comércio interno e internacional, com uma vocação às áreas consultivas e de arbitragem.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Flavio Morato Galvão ', 'Consultor empresarial para assuntos ambientais. Atuando na área desde 2005, já participou e coordenou diversos projetos, como os Estudos de Impacto Ambiental da Toyota, Hyundai e Honda, entre muito outros. Orientado ao desenvolvimento de estrategia de criação de valor, gestão de conflitos, e aplicação de inteligencia ambiental multidisciplinar.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Gerdau Aços Longos S.A', 'É líder no segmento de aços longos nas Américas e uma das principais fornecedoras de aços longos especiais do mundo. Recentemente, passou também a atuar em dois novos mercados no Brasil, com a produção própria de aços planos e a expansão das atividades de minério de ferro, iniciativas que estão ampliando o mix de produtos oferecidos ao mercado e a competitividade de suas operações. Possui operações industriais em 14 países – nas Américas, na Europa e na Ásia –, as quais somam uma capacidade instalada superior a 25 milhões de toneladas de aço por ano. Além disso, é a maior recicladora da América Latina e, no mundo, transforma, anualmente, milhões de toneladas de sucata em aço, reforçando seu compromisso com o desenvolvimento sustentável das regiões onde atua.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'GLV Brasil Ltda.', 'Projeta e comercializa equipamentos utilizados em vários estágios de produção de celulose e papel, desde a preparação de celulose para a formação da folha e acabamento. Fornece ao mercado global peças de reposição, recria upgrades e serviços de otimização para equipamentos novos e existentes. O grupo de celulose e papel é focado em inovação e fornece tecnologias que geram economia de energia e de custos.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'GoExport ', 'Empresa de serviços em comércio internacional. GoExport oferece suporte a seus clientes em projetos de exportação na América Latina. Nós nos especializamos no desenvolvimento comercial. Fundada ha 6 anos GoExport está sediada em Montreal e também tem escritórios no México e em Rio de Janeiro. GoExport assegura uma presença constante e regular em todos os países da América Latina permitindo, dessa maneira, acelerar o processo de implementação de empresas no exterior. Essencialmente GoExport executa vendas em nome de seus clientes.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Gran Tierra Energy Inc.', 'Exploração e produção de petróleo e gás empresa internacional com sede em Calgary, Canadá, incorporados e comercializados nos Estados Unidos e em operação na América do Sul. A Companhia detém atualmente participações na produção e propriedades prováveis &#8203;&#8203;na Colômbia, Peru e Brasil. A estratégia da empresa é focada em estabelecer um portfólio de oportunidades de perfuração para explorar reservas não desenvolvidas para aumentar a produção, bem como a realização de perfuração de exploração a crescer reservas futuras.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Grupo JMMS', 'É uma empresa de Engenharia especializada no desenvolvimento de mercados e geração de negócios voltados à Metalurgia, Mineração, Construção Civil e Engenharia Aduaneira.
Tratamento de minérios e comercialização de matéria-prima, realizando trabalhos no mercado nacional e internacional. Atuação no segmento de Engenharia para Comércio Exterior e Assessoria Comercial em Desenvolvimento de Mercados.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Grupo V. Santos ', 'Tem como objetivo coordenar todas as etapas que envolvem negociações de importação e exportação.
Ao longo desses anos a  V.Santos reuniu uma equipe de profissionais qualificados, especializados e principalmente atualizados para atender as necessidades e exigências dos clientes.
A nossa empresa tem como objetivo se tornar seu principal parceiro para soluções logísticas e assessoria em comércio exterior.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Guaranaap Tecnologia Ltda.', 'Desenvolvimento sob medida de soluções integradas para web e equipamentos móveis: smartphones e tablets.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Guilherme Maluf Corsino ', 'Guilherme Maluf Corsino (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Husky do Brasil Sistemas de Injeção Ltda', 'É a maior fornecedora de marca do mundo de injeção de equipamentos e serviços de moldagem para a indústria de plásticos. Com uma das linhas de produtos mais ampla da indústria, equipamentos Husky é usado para a fabricação de uma ampla gama de produtos plásticos, como garrafas e tampas para bebidas, recipientes para alimentos, componentes médicos e componentes eletrônicos de consumo.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Iamgold Brasil Ltda.', 'É um produtor de ouro mid-tier opera minas de ouro (incluindo joint ventures atuais) em três continentes e uma das três maiores minas de nióbio do mundo. A sólida base de ativos estratégicos no Canadá, América do Sul e África é complementada por projetos de desenvolvimento e de exploração e avaliação de oportunidades de aquisição agregue continuou. IAMGOLD está em uma posição financeira sólida, com manejo extensivo e experiência operacional.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Ingle International ', 'O Grupo Canadense Ingle fornece soluções de seguro de viagem personalizadas e serviços de assistência de emergência em todo o mundo desde 1946. A Ingle International pode encontrar o seguro certo para as necessidades únicas de cada viagem, para estudantes ou viajantes, em grupos ou individuais, de qualquer lugar para qualquer lugar do mundo.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Innovare Biotecnologia e Saúde Animal ', 'Criada em 2005, a Innovare possui uma área fabril capacitada para a terceirização de produtos de linhas hormonais não estéreis e conta com uma equipe multidisciplinar capaz de atender às mais diversas demandas de produção, pesquisa e desenvolvimento.
Com foco em inovação a empresa busca converter as possibilidades científicas em aplicações práticas de negócios.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Interlira Consultoria em Gestão de Riscos Ltda.', 'Ajudam as empresas bem-sucedidas criar, expandir e melhorar os seus negócios no Brasil e no exterior.
Desenvolvimento de Negócios & Serviços de Gerenciamento Executivo interino com custos justos e riscos compartilhados / recompensas .
IMG oferece habilidades gerenciais experientes, sob demanda, para empresas de diversos segmentos e tamanhos. Oferecem verdadeiras parcerias com os clientes, que resultam em longa duração, relações de confiança.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Intermanagement Consultoria Ltda. ', 'IMG oferece desenvolvimento de negócios e serviços de gerenciamento executivo interino  com custos justos, numa base de risco / recompensa compartilhados.
Ajudamos as empresas bem-sucedidas criar, expandir e melhorar os seus negócios no Brasil e no exterior.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Ita Representações Internacionais Ltda. ', 'É uma empresa de comércio internacional de alimentos.
Especializados em produtos lácteos, ingredientes e preparações alimentícias com base láctea e mantemos uma diversificada rede de fornecedores na América do Sul, Europa, EUA e Canadá.
Grande conhecimento tanto no aspecto marketing-comercial, como também na parte operacional (logística e documentação) de comercio exterior.
Atua principalmente no abastecimento do mercado brasileiro, com enfoque em redes de supermercados nacionais e regionais, indústrias alimentícias e atacadistas/distribuidores.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Joaquim Augusto Melo de Queiroz ', 'Joaquim Augusto Melo de Queiroz (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Kennedy Reial Linhares - Advocacia e Consultoria ', 'O escritório presta assessoria jurídica em diversos ramos do Direito, atuando na criação e implementação de soluções inovadoras e eficazes, com elevado conhecimento técnico. Possui credibilidade, reconhecida experiência em prestar serviços jurídicos ágeis e seguros. Presta assessoria e consultoria jurídica em todo o Nordeste do Brasil.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Kinross Brasil Mineração S.A.', 'Atua nas atividades de pesquisa e desenvolvimento mineral, mineração, beneficiamento e comercialização de ouro. É uma das maiores produtoras  de ouro do Brasil, responsável por 25% da produção nacional. Com operação na mina Morro do Ouro, em Paracatu, noroeste de Minas Gerais, e escritório em Belo Horizonte, a empresa integra a Kinross Gold Corporation, grupo canadense com presença na América do Sul (Brasil e Chile), América do Norte (Estados Unidos e Canadá), África (Gana e Mauritânia) e Eurásia (Rússia).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Kleber Cavalcanti Stefano', 'Advogado e Consultor Jurídico em Assuntos de Propriedade Intelectual (com ênfase em contratos tecnológicos) e Direito Societário. Mestre em Direito pela Universidade Metodista de Piracicaba (UNIMEP - 2009); Pós-Graduado "latu sensu" em Direito Constitucional pela Pontifícia Universidade Católica de Campinas (PUC-Campinas - 2004); Diplomado em Direito da Propriedade Intelectual pela Organização Mundial da Propriedade Intelectual (WIPO) e pela PUC-Campinas; Professor de Direito Empresarial e de Direito Internacional Privado do Centro Universitário Salesiano São Paulo - UNISAL - Campinas; Professor de Legislação Tributária e de Ética e Propriedade Intelectual das Faculdades - IMBEC / Metrocamp.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Leal Cotrim Jansen Advogados', 'É um escritório de advocacia constituído com o objetivo de prestar serviços jurídicos de elevada qualidade técnica. Com uma estrutura dimensionada para atender seus clientes de forma personalizada, a atuação do Leal Cotrim Advogados se perfaz em praticamente todas as áreas do direito nas quais a atividade empresarial exige assessoria jurídica especializada e sofisticada.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Lefosse Advogados', 'Oferece assessoria jurídica especializada em direito empresarial e finanças corporativas. Oferecemos entendimento das praticas legais e de negócios e um serviço consistente, caracterizado por uma equipe comprometida e preparada. Atuamos em algumas das mais complexas operações no pais para algumas das mais importantes empresas.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Litrans Logística Internacional de Transportes Ltda. ', 'Empresa de agenciamento de cargas marítimas e aéreas, habilitada para desconsolidação de cargas nos portos brasileiros e emissão de BL próprio.
Gestão completa das suas operações de importação e exportação, que inclui, além do despacho aduaneiro a consultoria e assessoria na área de logística , tributação e legislação aduaneira.
Agentes da CN Worldwide, empresa canadense líder em transporte ferroviário na America do Norte e hoje com serviço multimodal para o Brasil. A LITRANS se torna assim responsável pelo agenciamento documental e coordenação de liberação de suas cargas no destino.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Logica America do Sul, Soluções em Tecnologia Ltda. ', 'Profissionais em 40 países das Américas, Europa e Ásia-Pacífico que fornecem end-to-end serviços de TI e de processos de negócios que facilitam a evolução contínua dos negócios dos clientes.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Luis Augusto Mattiazzo Cardia', 'Advogado corporativo (contratos/societários/marcas), Grupo Lwart (www.lwart.com.br), Professor (Direito Civil), IESB-Preve - Bauru/SP.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Luis Cantieri', 'Luis Cantieri (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Machado Associados Advogados e Consultores', 'Atua nos principais nichos do Direito Empresarial há mais de 23 anos.
Perfil de boutique de advogados de negócios, assessorando os clientes de forma personalizada com uma equipe multidisciplinar que também possui conhecimento e experiência em economia e contabilidade. Esse perfil permite prestar um serviço de alta qualidade, abrangente e diferenciado, em linha com os interesses dos clientes, nas seguintes áreas do Direito: administrativa, auditorias legais, auditorias legais (due diligences completas), contratos, financiamento direto/mercado de capitais, imobiliária, importação e exportação, investimentos estrangeiros, petróleo e gás, societária/fusões e aquisições (M&A), trabalhista e previdenciária, tributária e contenciosa tributária.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Machado Meyer, Sendacz e Opice Advogados', 'Atua em todas as áreas do direito, oferece assistência legal a clientes nacionais e internacionais, incluindo grandes corporações dos mais variados setores de atividades, instituições financeiras e entidades governamentais.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Magalhães, Nery e Dias Advocacia', 'Escritório de advocacia especializado em Direito Econômico no Brasil.
Departamento especializado em antitruste do Brasil.
Ampla experiência na Advocacia Empresarial.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Manitoba Trade And Investment Corporation', 'A Manitoba Trade and Investment tem como objetivo o crescimento da economia em Manitoba.
Investe no aumento das exportações, na atração e retenção do investimento estrangeiro direto.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Marcelo Correa Consulting ', 'Aliando a larga experiência e conhecimento dos mercados canadense e brasileiro, a Marcelo Corrêa Consulting, empresa baseada em Toronto, se propôe a auxiliar empresas brasileiras que queiram explorar o mercado canadense. Análise de mercados, estruturação de empresas e negociações internacionais destacam-se entre os serviços prestados.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Marcos Eduardo Goiana Fedozzi', 'Marcos Eduardo Goiana Fedozzi (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Elidie Palma Bifano', '', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Mark Andrew Snow ', 'Mark Andrew Snow (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Mattos Muriel Kestener Advogados', 'Oferece assessoria jurídica a empresas nacionais e transnacionais nas principais áreas do Direito Empresarial.
 Prestam serviços jurídicos em questões de Direito Negocial, Regulatório, Consultivo e Contencioso.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Mccain do Brasil Alimentos Ltda', 'Empresa de origem canadense líder mundial em processamento e vendas de batatas pré-fritas congeladas.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Mellohawk Logistics Inc.', 'É uma empresa de logística internacional, especializada em transportes e serviços com operação em todo o mundo.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Metalúrgica Tuzzi Ltda. ', 'É uma empresa consolidada no Brasil com o foco no desenvolvimento global de soluções para diferentes mercados, em especial, o agrícola, além do automotivo, industrial, ferroviário e construção civil. Com parque fabril integrado, a Tuzzi conta com unidades de negócios modernas que desenvolvem e produzem peças e componentes para tratores de rodas e veículos pesados, laminados de aço e forjados a quente para diversas aplicações, atuando desde o estudo, projeto à produção das peças.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Metroliner Representações Imp. Exp. e Com. de Maq. e Equip. Ltda.', 'Mesas Alinhadoras de Chassis e Equipamentos para Funilaria e Pintura.
Tecnologia e qualidade para reparos automobilísticos, é uma empresa brasileira que atua no mercado de reparação automobilística.
Vende equipamentos de alta qualidade e tecnologia. Oferecem além de acessórios e equipamentos para reparação automobilística, vários tipos de ferramentas para funilaria e mecânica, além de prestação de serviços, treinamento e reciclagem para profissionais nas áreas de segurança do trabalho e meio ambiente.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Mineração Riacho dos Machados / Carpathian Gold Inc.', 'É uma companhia de exploração e desenvolvimento, cujo principal negócio é a extração de ouro e cobre.
Atua no Brasil em sua propriedade em Riacho dos Machados no Projeto de Ouro.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Mineração Serras do Oeste Ltda. / Jaguar Mine', 'É uma produtora de ouro com operações nos estados de Minas Gerais e Maranhão. Controla os recursos minerais em uma base de terra de cerca de 210 mil hectares que é o Projeto de Gurupi. É uma empresa canadense com o seu escritório principal em Toronto, Ontário. Tem escritório administrativo no Brasil em Belo Horizonte.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Mineração Vale Verde / Aura Minerals Inc.', 'É uma empresa canadense focada na aquisição, exploração, desenvolvimento e operação de propriedades de mineração nas Américas. A Mineração Vale Verde Ltda ., é uma das subsidiária brasileira da Aura Minerals Inc.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Mohr-Bell Business Planning Ltda.', 'Têm por finalidade oferecer serviços de assessoria de divulgação e treinamento, gerenciamento e gestão de empresas e orientação estratégica de negócios com qualidade a seus clientes.
Um dos focos de atuação é o de apoiar e incentivar o intercâmbio comercial e de investimentos entre o Brasil e alguns países selecionados. Isto é oferecido através da apresentação das informações principais a respeito dos respectivos mercados e ambiente de negócios, assessorando os empresários interessados na análise e preparação de estratégias.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Mundie e Advogados', 'Tem como objetivo prestar serviços jurídicos de alto nível a clientes nacionais e estrangeiros. O escritório atua em todas as áreas do direito empresarial, tem um perfil jovem e dinâmico e é reconhecido por seu profissionalismo e por sua abordagem moderna e objetiva da advocacia.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Murray Advogados ', 'Atua em todas as áreas do Direito Empresarial, tanto no Brasil como no exterior. Assessoramento legal a empresas nacionais e estrangeiras.
Membro do PLG International Lawyers E.E.I.G (“PLG”). O PLG é uma associação internacional composta de Escritórios de Advocacia, com sede administrativa em Bruxelas.
Membro da Rex Sport Association, que tem sede em Barcelona.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Nadia de Araujo Advogados', 'O escritório é especializado na área de direito internacional, e soluciona questões jurídicas relacionadas a operações comerciais e ao direito de família/sucessões. Na esfera empresarial, a atuação envolve a elaboração de contratos, pareceres, affidavits e análises de direito comparado, bem como a condução de ações de homologação de sentenças estrangeiras e de procedimentos de solução de controvérsias. No ramo de família, o auxílio jurídico compreende demandas relativas à sucessão internacional, sequestro de menores, cobrança de alimentos, divórcio, dentre outras.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Nasser Belalia ', 'Nasser Belalia (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'National Bank of Canadá', 'Sede na rue Saint-Pierre, distrito bancário de Quebec City.
Oferecer serviços aos seus clientes de varejo e de negócios bancários.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'OM International Ltda. ', 'Empresa de importação e exportação de produtos alimentícios. Com área de serviços de consultoria e negócios internacionais e jurídica.  ', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Paseli Consultoria ', 'É uma única consultoria com atuação global. Oferecemos solução completa para empresas que queiram vender para o governo brasileiro, como para as que queiram se estabelecer no país.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Paulo André de Souza da Silva ', 'Paulo Andre de Souza da Silva (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Paulo Dominonni', 'Paulo Dominonni (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Paulo Henrique Apsan', '“Consultor,  com mais de 30 anos de experiência em Planejamento Estratégico e Governança Corporativa. Trabalhou na Booz, Allen&Hamilton em São Paulo e em Chicago, e atuou como responsável pelos escritórios brasileiros da  Gemini Consulting e da Arthur D. Little no Brasil. Atualmente é sócio-titular da Apsan Consultoria”', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Perrotti e Barrueco Advogados Associados', 'Atua no assessoramento jurídico-empresarial, tanto no âmbito consultivo quanto no contencioso, em processos litigiosos ou de caráter preventivo. ', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Pinheiro Neto Advogados', 'Um escritório full service com alto nível de especialização nas diferentes práticas do direito. A atuação diversificada, aliada a ampla rede de correspondentes no Brasil e excelente relacionamento com agentes internacionais, oferecem soluções abrangentes para qualquer questão jurídica.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Powerpack Representações Com. Ltda', 'Atua como representante comercial exclusivo no território Brasileiro de tradicionais empresas estrangeiras, fornecedoras de produtos para as áreas da aviação civil e militar e de defesa.
Atualmente Powerpack representa as seguintes empresas:
- Sikorsky Aircraft (Aviação)
- Pratt & Whitney Canada (Aviação)
- CAE (Simulação)
- L3 MAPPS (Simulação)
- Simunition (Defesa)
- Colt Defense (Defesa)
- Pall Aerospace (Aviação)
- Zodiac Aerospace - Monogram Systems (TIA Division) - (Aviação).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'PriceWaterhouseCoopers Brasil', 'A PWC tem um objetivo claro: ser a empresa líder em serviços profissionais no mundo. Por essa razão investimos constantemente na qualidade dos serviços prestados para que atendam com excelência as necessidades de nossos clientes. No Brasil, somos 5.000 profissionais das mais variadas formações e talentos, distribuídos em 17 escritórios, mantendo assim, uma rede de alcance nacional.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Rafael Busto Infante ', 'Rafael Busto Infante (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Raul Felipe Cairoli Papaleo', 'Raul Felipe Cairoli Papaleo (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'RBC Brasil Distribuidora de Títulos e Valores Mobiliários Ltda', 'Provedora de serviços financeiros globais, servindo indivíduos com alto patrimônio líquido e nicho de empresas e clientes institucionais em todo o mundo. ', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Ricardo Arce ', 'Ricardo Arce (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Rio Tinto Alcan', 'Rio Tinto Alcan é a líder global no negócio de alumínio. É um dos maiores produtores mundiais de bauxita, alumina e alumínio.
A Rio Tinto Alcan Brazil é um dos cinco grupos operados pela Rio Tinto, uma empresa canadense líder internacional de mineração.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Rodrigo Cesar de Pinho ', 'Rodrigo Cesar de Pinho (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Rodrigo Ribeiro Lima ', 'Rodrigo Ribeiro Lima (Pessoa Física).', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Rolls-Royce Brasil Ltda', 'Motores aeronáuticos, aviões de passageiros mais avançados do mundo, como o novo Airbus A350 e Boeing 787 Dreamliner.
Também produzir sistemas de energia de baixa emissão para navios, alguns dos quais com projetos próprios.
Veículos terrestres: variando de trens para colheitadeiras, e construção de motores para a geração de energia elétrica.
Manutenção dos sistemas de energia.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Royal Bank Of Canada - Weath Management', 'Banco canadense - RBC é uma das principais empresas de serviços financeiros diversificados da América do Norte que prestam serviços bancários, gestão de fortunas, seguros e mercados de capitais serviços em uma base global.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Santos Bay Transportes Ltda.', 'Focada no transporte de mercadorias relacionadas ao comércio exterior.
Especializada no segmento transporte rodoviário sobre eixos, Municipal, Intermunicipal, Estadual além da movimentação de Contêineres. Atualmente a empresa concentra suas operações no Porto de Santos/SP, nos aeroportos de Guarulhos e Campinas.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Scotiabank Brasil S.A. Banco Múltiplo', 'Operam no Brasil desde o início dos anos 70.
Oferece uma ampla gama de produtos e serviços de corporate e investment banking e capital markets.
É um banco canadense que oferece uma variedade de produtos e serviços diversificados para aproximadamente 18,6 milhões de consumidores em mais de 50 países ao redor do mundo.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Sidera Estratégistas - Acesso e Exp. de Mercados Ltda.', 'Consultoria em comercio internacional que atua nas áreas de defesa comercial, analise de viabilidade de implantação e expansão de negócios, acesso a mercados, compras governamentais, negociações bilaterais e multilaterais, planejamento estratégico, questões de conformidade e reengenharia aduaneira, além da capacitação empresarial e governamental.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Soluções em Pavimentação e Locações de Equipamentos ', 'Empresa que projeta, desenvolve e opera equipamentos de reposição asfaltica, soluções em saneamento básico e limpeza urbana.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Straube Advogados', 'Presta serviços jurídicos personalizados, independentemente do porte ou ramo de atividade de seus clientes, destacando-se pela sua tradição e pela reunião de uma equipe especializada, com advogados que atuam inclusive no âmbito internacional. Essa experiência possibilita o atendimento às necessidades de empresas nacionais e estrangeiras, como também de pessoas físicas, nos mais variados ramos do Direito.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Tess Advogados', 'Profissionais que atuam como professores, árbitros e mediadores, e que participam das mais representativas entidades nacionais e internacionais.
É um escritório engajado e criativo, sempre atento ao que ocorre no mundo do Direito e dos negócios.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Tillity Cosméticos Eireli', 'Empresa 100% brasileira, que comercializa produtos naturais à base de própolis verde.
A própolis verde é reconhecida mundialmente como eficiente anti-inflamatório e antisséptico (antimicrobiano). Atua como cicatrizante e regeneradora de tecidos, pois apresenta qualidades antifúngicas, antiviróticas e antibacterianas, com eficácia até no combate a protozoários.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Totalfinishing Equipamentos e Abrasivos Ltda. ', 'Desenvolve máquinas e produtos para tratamento de superfície, da fase de remoção de rebarbas até o brilho final. Nossa qualidade e credibilidade nos permitem atender a fornecedores de vários segmentos, como indústria moveleira, de equipamentos médico-odontológicos, joalheria, calçadista, automobilistica, entre outros. Fornecendo processos completos para o tratamento de uma infinidade de produtos, como autopeças, jóias, armações de óculos, instrumentos musicais, metais sanitários, entre outros.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Tozzini Freire Advogados', 'É uma organização de serviços jurídicos líder na América Latina, com atuação em todas as áreas do direito empresarial e histórico de sucesso no atendimento a empresas nacionais e internacionais. Com unidades próprias em diversas cidades do Brasil, garantimos aos nossos clientes um padrão único de qualidade e atendimento.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Trench, Rossi e Watanabe Advogados', 'Um dos maiores escritórios de advocacia do Brasil, possui uma atuação abrangente e conceituada, com competência em todas as áreas do direito.
Serviços legais para clientes nacionais e internacionais, dos mais diversos mercados, auxiliando-os no gerenciamento de seus negócios de maneira ética e eficiente.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Triton Logging', 'Projetos de avaliação, pesquisas e remediação em reservatórios de hidrelétricas, retirada de florestas submersas em larga escala, líder mundial em tecnologia para recuperação de madeira submersa em reservatórios de hidrelétricas.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'United Safety Serviços de Segurança Industrial Ltda. ', 'É uma empresa com mais de 25 anos de experiência no ramo de segurança industrial. Original do Canadá, nosso core business esta na instalação de serviços em detecção de gases perigosos, consultoria e gerenciamento de risco.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Vale S.A.', 'É uma mineradora global que descobre e transforma minerais essenciais para o nosso dia a dia. Presente em 37 países, é líder mundial na produção de minério de ferro, segunda maior produtora de níquel e uma das principais produtoras de manganês, fertilizantes, cobre e carvão. Atua também em logística, energia e siderurgia, esforçando-se para superar os padrões consagrados de excelência em pesquisa, desenvolvimento, implantação de projetos e operação de negócios. 

Cada um dos 139 mil empregados da Vale em todo o mundo trabalha diariamente com uma mesma missão: transformar recursos naturais em riqueza e desenvolvimento sustentável, garantindo assim um legado econômico, social e ambiental às futuras gerações. ', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Veirano Advogados', 'É um escritório com atuação em todas as áreas de prática do direito empresarial. Com presença no Rio de Janeiro, São Paulo, Rio Grande do Sul e Brasília, representam empresas no Brasil e internacionalmente com o suporte de uma rede de parceiros presentes em mais de 120 países, incluindo relacionamentos valiosos nos principais centros de negócios do mundo.
Atuam com foco em simplificar operações nacionais e internacionais e gerar os resultados desejados.
Participam de várias organizações jurídicas internacionais, dentre as quais World Services Group (WSG), TAGLaw e Ius Laboris. WSG é uma rede global que promove a troca de experiências entre escritórios de advocacia em mais de 115 países.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Velours International ', '', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Vertebratta Comunica Ltda. ', 'Especialista em desenvolver e implementar estratégias de marketing, propaganda, publicidade e comunicação no mercado brasileiro, por meio de uma aproximação em multicanais. A Vertebratta é um grupo de serviços que combina, desde 2001, inovação e gestão para expansão e maximização dos investimentos dos seus clientes. ', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Viabilis do Brasil Consultoria Ltda. ', 'Atividades de Consultoria em Gestão Empresarial, exceto Consultoria Técnica específica.
Representantes comerciais e agentes do comércio de mercadorias em geral não especializados.
Atividades de intermediação e agenciamento de serviços e negócios em geral, exceto imobiliários.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Votorantim Cimentos Ltda.', 'Maior produtor de cimento do Brasil.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'World Limes Comércio e Exportação de Frutas ', 'Comércio Varejista de Hortifrutigranjeiros.
Comércio atacadista de frutas, verduras, raízes, tubérculos, hortaliças e legumes frescos.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Yamana Gold', 'É uma produtora canadense de ouro com significativa produção, projetos em desenvolvimento e projetos exploratórios nas Américas, incluindo Brasil, Argentina, Chile e México. A Yamana planeja continuar crescendo através de expansões nas minas existentes, desenvolvimento de novas minas e avançando em seus projetos exploratórios.', 1, 1, 1)
Insert Into tblAssociado(SiteId, Nome, Resumo, AssociadoCategoriaId, TipoPessoaId, PaisId) Values(1, 'Zimmcor Holdings', 'É uma empresa privada em termos de investimentos, localizada em Montreal, Canadá. Estamos focada em vários setores, inclusivo tecnologia e e-Commerce nos mercados canadense e internacional. ', 1, 1, 1)
